### ISSUE TITLE
PROYECTO PULSADOR-ERICK

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/proyecto-pulsador-equipo-de-uriel-edwin-araceli-1as#3]
[Proyecto Pulsador.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-equipo-de-uriel-edwin-araceli-1as/files/7819493/Proyecto.Pulsador.pdf)

**Comment by josealfredo79** [comment]
Falto hacerlo físico el proyecto

**Comment by josealfredo79** [comment]
Revisado
